graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "K"
      graphics [
         x 50
         y 50
      ]
   ]
   node [
      id 1
      label "K"
      graphics [
         x 140
         y 50
      ]
   ]
   node [
      id 2
      label "K"
      graphics [
         x 320
         y 50
      ]
   ]
   node [
      id 3
      label "K"
      graphics [
         x 230
         y 50
      ]
   ]
   node [
      id 4
      label "K"
      graphics [
         x 230
         y 140
      ]
   ]
   node [
      id 5
      label "K"
      graphics [
         x 140
         y 140
      ]
   ]
   node [
      id 6
      label "K"
      graphics [
         x 50
         y 140
      ]
   ]
   node [
      id 7
      label "K"
      graphics [
         x 50
         y 230
      ]
   ]
   node [
      id 8
      label "K"
      graphics [
         x 50
         y 320
      ]
   ]
   node [
      id 9
      label "K"
      graphics [
         x 140
         y 320
      ]
   ]
   node [
      id 10
      label "K"
      graphics [
         x 140
         y 230
      ]
   ]
   node [
      id 11
      label "K"
      graphics [
         x 230
         y 230
      ]
   ]
   node [
      id 12
      label "K"
      graphics [
         x 320
         y 140
      ]
   ]
   node [
      id 13
      label "K"
      graphics [
         x 320
         y 230
      ]
   ]
   node [
      id 14
      label "K"
      graphics [
         x 320
         y 320
      ]
   ]
   node [
      id 15
      label "K"
      graphics [
         x 230
         y 320
      ]
   ]
]