graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "K"
      graphics [
         x 320
         y 230
      ]
   ]
   node [
      id 1
      label "K"
      graphics [
         x 350
         y 200
      ]
   ]
   node [
      id 2
      label "K"
      graphics [
         x 410
         y 200
      ]
   ]
   node [
      id 3
      label "K"
      graphics [
         x 470
         y 200
      ]
   ]
   node [
      id 4
      label "K"
      graphics [
         x 470
         y 260
      ]
   ]
   node [
      id 5
      label "K"
      graphics [
         x 410
         y 260
      ]
   ]
   node [
      id 6
      label "K"
      graphics [
         x 350
         y 260
      ]
   ]
]