graph [
       comment "Generated by ViSiDiA"
directed 0
   node [
      id 0
      label "T"
      graphics [
         x 0
         y 0
      ]
   ]
   node [
      id 1
      label "T"
      graphics [
         x 500
         y 0
      ]
   ]
   node [
      id 2
      label "T"
      graphics [
         x 0
         y 500
      ]
   ]
   node [
      id 3
      label "T"
      graphics [
         x 500
         y 500
      ]
   ]
   node [
      id 4
      label "C"
      graphics [
         x 349
         y 473
      ]
   ]
   node [
      id 5
      label "C"
      graphics [
         x 138
         y 4
      ]
   ]
   node [
      id 6
      label "C"
      graphics [
         x 253
         y 44
      ]
   ]
   node [
      id 7
      label "C"
      graphics [
         x 335
         y 44
      ]
   ]
   node [
      id 8
      label "C"
      graphics [
         x 12
         y 84
      ]
   ]
   node [
      id 9
      label "C"
      graphics [
         x 41
         y 73
      ]
   ]
   edge [
      source 0
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
]