graph [
       comment "Generated by ViSiDiA"
directed 0
   node [
      id 0
      label "T"
      graphics [
         x 0
         y 0
      ]
   ]
   node [
      id 1
      label "T"
      graphics [
         x 500
         y 0
      ]
   ]
   node [
      id 2
      label "T"
      graphics [
         x 0
         y 500
      ]
   ]
   node [
      id 3
      label "T"
      graphics [
         x 500
         y 500
      ]
   ]
   node [
      id 4
      label "C"
      graphics [
         x 354
         y 416
      ]
   ]
   node [
      id 5
      label "C"
      graphics [
         x 486
         y 485
      ]
   ]
   node [
      id 6
      label "C"
      graphics [
         x 347
         y 489
      ]
   ]
   node [
      id 7
      label "C"
      graphics [
         x 341
         y 115
      ]
   ]
   node [
      id 8
      label "C"
      graphics [
         x 42
         y 498
      ]
   ]
   node [
      id 9
      label "C"
      graphics [
         x 231
         y 403
      ]
   ]
   edge [
      source 3
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 4
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 6
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 4
      label ""
      weight 1.0
   ]
   edge [
      source 5
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 3
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 7
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 5
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 8
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 3
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 6
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 7
      label ""
      weight 1.0
   ]
   edge [
      source 8
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 4
      label ""
      weight 1.0
   ]
]