graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "K"
      graphics [
         x 50
         y 50
      ]
   ]
   node [
      id 1
      label "K"
      graphics [
         x 920
         y 50
      ]
   ]
   node [
      id 2
      label "K"
      graphics [
         x 80
         y 50
      ]
   ]
   node [
      id 3
      label "K"
      graphics [
         x 80
         y 80
      ]
   ]
   node [
      id 4
      label "K"
      graphics [
         x 350
         y 290
      ]
   ]
   node [
      id 5
      label "K"
      graphics [
         x 410
         y 290
      ]
   ]
   node [
      id 6
      label "K"
      graphics [
         x 440
         y 290
      ]
   ]
   node [
      id 7
      label "K"
      graphics [
         x 590
         y 290
      ]
   ]
]