graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "K"
      graphics [
         x 192
         y 114
      ]
   ]
   node [
      id 9
      label "K"
      graphics [
         x 1140
         y 124
      ]
   ]
   node [
      id 10
      label "K"
      graphics [
         x 200
         y 510
      ]
   ]
   node [
      id 11
      label "K"
      graphics [
         x 1044
         y 470
      ]
   ]
   node [
      id 12
      label "K"
      graphics [
         x 911
         y 348
      ]
   ]
   node [
      id 13
      label "K"
      graphics [
         x 735
         y 177
      ]
   ]
   node [
      id 14
      label "K"
      graphics [
         x 587
         y 167
      ]
   ]
   node [
      id 15
      label "K"
      graphics [
         x 465
         y 152
      ]
   ]
   node [
      id 16
      label "K"
      graphics [
         x 406
         y 249
      ]
   ]
   node [
      id 19
      label "K"
      graphics [
         x 639
         y 414
      ]
   ]
   node [
      id 23
      label "K"
      graphics [
         x 908
         y 230
      ]
   ]
   node [
      id 25
      label "K"
      graphics [
         x 829
         y 199
      ]
   ]
   node [
      id 27
      label "K"
      graphics [
         x 857
         y 109
      ]
   ]
   node [
      id 29
      label "K"
      graphics [
         x 789
         y 118
      ]
   ]
   node [
      id 34
      label "K"
      graphics [
         x 470
         y 370
      ]
   ]
   node [
      id 36
      label "K"
      graphics [
         x 301
         y 412
      ]
   ]
   node [
      id 37
      label "K"
      graphics [
         x 211
         y 337
      ]
   ]
   node [
      id 39
      label "K"
      graphics [
         x 347
         y 479
      ]
   ]
   node [
      id 41
      label "K"
      graphics [
         x 436
         y 417
      ]
   ]
   node [
      id 43
      label "K"
      graphics [
         x 511
         y 451
      ]
   ]
   node [
      id 45
      label "K"
      graphics [
         x 440
         y 492
      ]
   ]
   node [
      id 49
      label "K"
      graphics [
         x 903
         y 459
      ]
   ]
   node [
      id 53
      label "K"
      graphics [
         x 640
         y 485
      ]
   ]
   node [
      id 55
      label "K"
      graphics [
         x 510
         y 511
      ]
   ]
   node [
      id 59
      label "K"
      graphics [
         x 1140
         y 239
      ]
   ]
   node [
      id 60
      label "K"
      graphics [
         x 966
         y 305
      ]
   ]
   node [
      id 65
      label "K"
      graphics [
         x 446
         y 72
      ]
   ]
   node [
      id 66
      label "K"
      graphics [
         x 576
         y 54
      ]
   ]
   node [
      id 67
      label "K"
      graphics [
         x 347
         y 149
      ]
   ]
   node [
      id 77
      label "K"
      graphics [
         x 291
         y 219
      ]
   ]
   node [
      id 78
      label "K"
      graphics [
         x 250
         y 293
      ]
   ]
   edge [
      source 15
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 16
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 19
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 9
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 23
      label ""
      weight 1.0
   ]
   edge [
      source 23
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 25
      label ""
      weight 1.0
   ]
   edge [
      source 25
      target 23
      label ""
      weight 1.0
   ]
   edge [
      source 23
      target 27
      label ""
      weight 1.0
   ]
   edge [
      source 27
      target 25
      label ""
      weight 1.0
   ]
   edge [
      source 25
      target 29
      label ""
      weight 1.0
   ]
   edge [
      source 29
      target 13
      label ""
      weight 1.0
   ]
   edge [
      source 13
      target 25
      label ""
      weight 1.0
   ]
   edge [
      source 25
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 19
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 34
      label ""
      weight 1.0
   ]
   edge [
      source 34
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 16
      target 36
      label ""
      weight 1.0
   ]
   edge [
      source 36
      target 37
      label ""
      weight 1.0
   ]
   edge [
      source 37
      target 10
      label ""
      weight 1.0
   ]
   edge [
      source 10
      target 39
      label ""
      weight 1.0
   ]
   edge [
      source 39
      target 36
      label ""
      weight 1.0
   ]
   edge [
      source 36
      target 41
      label ""
      weight 1.0
   ]
   edge [
      source 41
      target 34
      label ""
      weight 1.0
   ]
   edge [
      source 34
      target 43
      label ""
      weight 1.0
   ]
   edge [
      source 43
      target 41
      label ""
      weight 1.0
   ]
   edge [
      source 41
      target 45
      label ""
      weight 1.0
   ]
   edge [
      source 45
      target 39
      label ""
      weight 1.0
   ]
   edge [
      source 45
      target 43
      label ""
      weight 1.0
   ]
   edge [
      source 43
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 19
      target 49
      label ""
      weight 1.0
   ]
   edge [
      source 49
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 12
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 11
      target 49
      label ""
      weight 1.0
   ]
   edge [
      source 49
      target 53
      label ""
      weight 1.0
   ]
   edge [
      source 53
      target 43
      label ""
      weight 1.0
   ]
   edge [
      source 43
      target 55
      label ""
      weight 1.0
   ]
   edge [
      source 55
      target 45
      label ""
      weight 1.0
   ]
   edge [
      source 55
      target 53
      label ""
      weight 1.0
   ]
   edge [
      source 53
      target 19
      label ""
      weight 1.0
   ]
   edge [
      source 9
      target 59
      label ""
      weight 1.0
   ]
   edge [
      source 59
      target 60
      label ""
      weight 1.0
   ]
   edge [
      source 60
      target 23
      label ""
      weight 1.0
   ]
   edge [
      source 60
      target 12
      label ""
      weight 1.0
   ]
   edge [
      source 60
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 59
      target 11
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 65
      label ""
      weight 1.0
   ]
   edge [
      source 65
      target 66
      label ""
      weight 1.0
   ]
   edge [
      source 66
      target 67
      label ""
      weight 1.0
   ]
   edge [
      source 67
      target 65
      label ""
      weight 1.0
   ]
   edge [
      source 65
      target 15
      label ""
      weight 1.0
   ]
   edge [
      source 15
      target 67
      label ""
      weight 1.0
   ]
   edge [
      source 67
      target 16
      label ""
      weight 1.0
   ]
   edge [
      source 15
      target 66
      label ""
      weight 1.0
   ]
   edge [
      source 66
      target 14
      label ""
      weight 1.0
   ]
   edge [
      source 14
      target 15
      label ""
      weight 1.0
   ]
   edge [
      source 67
      target 0
      label ""
      weight 1.0
   ]
   edge [
      source 0
      target 37
      label ""
      weight 1.0
   ]
   edge [
      source 67
      target 77
      label ""
      weight 1.0
   ]
   edge [
      source 77
      target 78
      label ""
      weight 1.0
   ]
   edge [
      source 78
      target 36
      label ""
      weight 1.0
   ]
   edge [
      source 78
      target 37
      label ""
      weight 1.0
   ]
]