graph [
   comment "Generated by ViSiDiA" 
   directed 0
   node [
      id 0
      label "K"
      graphics [
         x 154
         y 110
      ]
   ]
   node [
      id 1
      label "K"
      graphics [
         x 341
         y 144
      ]
   ]
   node [
      id 2
      label "K"
      graphics [
         x 240
         y 264
      ]
   ]
   edge [
      source 0
      target 1
      label ""
      weight 1.0
   ]
   edge [
      source 1
      target 2
      label ""
      weight 1.0
   ]
   edge [
      source 2
      target 0
      label ""
      weight 1.0
   ]
]